### ISSUE TITLE
Can't query data when using ES 1.4

### ISSUE THREAD

**Issue by thomasvdb** [royrusso/elasticsearch-HQ#176]
When trying to query the indices I sometimes get the following error:
Uncaught TypeError: Cannot read property 'totalHits' of undefined

![2014-11-10_0841](https://cloud.githubusercontent.com/assets/1577109/4972515/0ce6a390-68ad-11e4-85c0-fe173f6a5642.png)

It appears that it only occurs when searching on one index.
The error doesn't occur when searching through multiple indices.

Elastic Search version is 1.4

**Comment by davidhoyt** [comment]
I am seeing this as well. Added a second index and it worked.
