### ISSUE TITLE
I can't connect to the server success

### ISSUE THREAD

**Issue by jinou624** [royrusso/elasticsearch-HQ#192]
I'm very sorry to ask a question in issues, because I was in china, I can not visit google.com site,so I can not read the Community.
If that's all right,can I have a email with yours?My email address is "jinou624@163.com".

Here is the install step,
1. Down load the zip file from the github
https://github.com/royrusso/elasticsearch-HQ/archive/master.zip
2.unzip the file
3.move the folder to the Elasticsearch server(/home/elasticsearch/plugins/HQ/_site/......)
4.open the url:http://172.17.0.179:9200/_plugin/HQ/
5.when I try to connect with "http://172.17.0.179:9200",it always is connecting status as the image:
![image](https://cloud.githubusercontent.com/assets/7298126/7875670/6fc4ff24-05f2-11e5-8c1f-236098ae475a.png)
How should I do?

etc,the elasticsearch server host is 172.17.0.179,and the elasticsearch service is available:
{
  "status" : 200,
  "name" : "es_172.17.0.179",
  "cluster_name" : "es_taochecar",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by heblug** [comment]
问题解决了吗？

**Comment by jinou624** [comment]
No

**Comment by Ryuchen** [comment]
请问问题解决了吗？

**Comment by mac119** [comment]
请问  问题 解决 了吗？？他这个 是不是 不支持 es 1.4.x 啊 ？

**Comment by jinou624** [comment]
没有解决，怀疑是版本支持度的问题，目前先用marvel和bigdesk来监控服务器性能状态了

**Comment by robertliu1988** [comment]
不知道大家遇到的问题是否和我一样，如果和我问题一样，那问题应该是出在 代码里面有特殊字符

![qq 20150716010813](https://cloud.githubusercontent.com/assets/6705667/8704708/5545e8e0-2b57-11e5-95b6-94935c0a7b5b.png)


参见   最新代码的908行，这些货币符号应该是没办法识别导致出错了，最简单的方法就是直接注释了就ok了
 ts.addParser({
        id: "currency",
        is: function (s) {
            return /^[£$€?.]/.test(s);
        }, format: function (s) {
            return $.tablesorter.formatFloat(s.replace(new RegExp(/[£$€]/g), ""));
        }, type: "numeric"
    });*/

**Comment by jackieMaKing** [comment]
问题解决了吗，@robertliu1988你修改的是哪个文件

**Comment by robertliu1988** [comment]
@jackieMaKing   修改 https://github.com/royrusso/elasticsearch-HQ/blob/master/js/lib/jquery/jquery.tablesorter.js  的908行，注释掉就行了

**Comment by iswin** [comment]
调整下浏览器编码，选择自动检测就OK了，这个问题困扰了我好久了！

**Comment by lostsnow** [comment]
html 页面没有声明 charset 啊!!

**Comment by lostsnow** [comment]
The character encoding of the HTML document was not declared:

```html
<meta charset='utf-8'>
```

**Comment by luckiss** [comment]
搞了半天原因是编码的问题XD

**Comment by hery-168** [comment]
把浏览器编码改成utf-8就ok了

**Comment by jinou624** [comment]
刚发现后面这些回复，果然是编码问题，哎，多谢robertliu1988

**Comment by liuzhenan** [comment]
谢谢各位前辈指路
