### ISSUE TITLE
can't define my own query in REST Editor

### ISSUE THREAD

**Issue by jackieMaKing** [royrusso/elasticsearch-HQ#195]
I am a green hand to ElasticHQ. I find REST Editor can't realize user-defined queries. It just support predefined queries in the drop-down box .
![image](https://cloud.githubusercontent.com/assets/4318313/8950947/97a135f2-35fa-11e5-827e-25e331e8a581.png)

 Does anybody encounter the same problem? How to solve it?

**Comment by royrusso** [comment]
Duplicate of #200
