### ISSUE TITLE
Installing on ES 2.0.0-beta2 error

### ISSUE THREAD

**Issue by silvestrelosada** [royrusso/elasticsearch-HQ#205]
Verifying https://github.com/royrusso/elasticsearch-HQ/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by nishaaaaa** [comment]
I am also facing the same issue.

**Comment by sebfek** [comment]
Same issue here. Elasticsearch Beta 2 also.

**Comment by AlexeyKosov** [comment]
Elasticsearch RC1

Verifying https://github.com/royrusso/elasticsearch-HQ/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by damienbod** [comment]
Same issue, in Elasticsearch RC1
Greetings Damien

**Comment by royrusso** [comment]
There are other issues with 2.x that I need to look at, but the install works now:

./plugin install royrusso/elasticsearch-HQ
-> Installing royrusso/elasticsearch-HQ...
Trying https://github.com/royrusso/elasticsearch-HQ/archive/master.zip ...
Downloading ...............................................................
Verifying https://github.com/royrusso/elasticsearch-HQ/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
Installed hq into /Users/royrusso/Downloads/elasticsearch-2.0.0-rc1/plugins/hq
