### ISSUE TITLE
Latest commit break all.min.js

### ISSUE THREAD

**Issue by gallart** [royrusso/elasticsearch-HQ#210]
Hi,

Latest commit is breaking javascript :

![image](https://cloud.githubusercontent.com/assets/2728195/10762557/d4677434-7cc6-11e5-8063-e0f37c775a68.png)

Can you roll-back ?

**Comment by royrusso** [comment]
Try now. I'm not seeing that. Is it on a specific screen?

**Comment by gallart** [comment]
See there :

https://github.com/royrusso/elasticsearch-HQ/blob/50fc1abb4735d50982aa4fd623cf59e447a8473f/js/all.min.js

Git conflicts are commited.

**Comment by royrusso** [comment]
Well that's just stupid. Let me check it out. ;-)

**Comment by royrusso** [comment]
Found a bug in the build attributed to node while fixing the original merge issue.
