### ISSUE TITLE
404 on lodash.min.js in most recent update.

### ISSUE THREAD

**Issue by tomarus** [royrusso/elasticsearch-HQ#215]
Hi the most recent update from today returns a 404 in lodash.min.js

As it seems it's not copied to the _site directory. I use elasticsearch/plugin install method to install the plugin.

A small temporary fix for myself was to copy the lodash dir to the _site dir using cp -a js/lib/lodash _site/js/lib/

But you might want to look into this :)

Thanks

**Comment by fbaligand** [comment]
+1

**Comment by fbaligand** [comment]
Thank you @royrusso !
With version 2.0.1, it works like a charm !

**Comment by tomarus** [comment]
Yes, thanks for the quick fix!
