### ISSUE TITLE
Indices management don't work

### ISSUE THREAD

**Issue by 21xhipster** [royrusso/elasticsearch-HQ#221]
It seems that everything works perfectly fine, but indices button is stuck.
Console:
![screen shot 2015-11-08 at 17 00 06](https://cloud.githubusercontent.com/assets/410789/11021486/36a2b768-863a-11e5-876f-5902633f19a6.png)
Elastic 1.5.
HQ works as plugin
Client don't matter. Tried Safari, Firefox, Chrome
Regards for any help

**Comment by royrusso** [comment]
Did you install recently from master?
