### ISSUE TITLE
Is there a way to disable polling?

### ISSUE THREAD

**Issue by fizmat** [royrusso/elasticsearch-HQ#222]
With a large cluster state and a slow browser connection, HQ becomes unusable as subsequent automatic requests pile up on top of each other. Either detect this and stop resending requests, or give a prominent button to stop this madness. Why is polling on by default in the first place? The "head" plugin went with a much more sensible auto-refresh off by default, and a button to turn it on.

**Comment by royrusso** [comment]
You can adjust the polling interval under settings. I'll create an issue for disabling it entirely.
