### ISSUE TITLE
Connecting to AWS ES from whitelisted IP resulting in CORS 403 issue

### ISSUE THREAD

**Issue by innovia** [royrusso/elasticsearch-HQ#227]
I have an instance which i installed the stand alone version on

the same instance is running a standalone kibana, and kibana  can also make AJAX requests to AWS ES, and it works because kibana is using kbn-xsrf-token header which allows cross domain,

How can i use the same way of this token, because AWS ES is not allowing to change the CORS config to allow CORS  and am really used to working with this plugin

**Comment by royrusso** [comment]
You may want to ask on the AWS forum (https://forums.aws.amazon.com/forum.jspa?forumID=200)

I tried using ES AWS, and the lack of decent security filtering and options made me kill the cluster. That think looks like an alpha version by AWS.

**Comment by innovia** [comment]
its secured by policy, what makes me think that its an issue with the plugin is that kibana stand alone is able to access AWS ES with the xsrf token, i wonder how they do that and if that can be used on your plugin as well

**Comment by royrusso** [comment]
AWS decided to only install and allow kibana as a plugin. They have added CORS and custom tokens like this just for that plugin. So far as I know, AWS doesn't support any other plugin being installed and you cannot modify the CORS attributes in the yml.
