### ISSUE TITLE
tokenizeUserPassFromURL is not a function

### ISSUE THREAD

**Issue by hery-168** [royrusso/elasticsearch-HQ#228]
when i connect the  ElasticSearch clusters failed ,Could not parse URL for auth credentials! tokenizeUserPassFromURL is not a function

**Comment by hery-168** [comment]
有可能是浏览器编码的问题，修改为utf-8ok了

**Comment by kristekw** [comment]
Baidu is too lame to find this topic! I've got stuck on this for nearly a week! till i climbed over the F**king GFW and google it!
