### ISSUE TITLE
elasticsearch HQ can not be used base on ES2.0.0

### ISSUE THREAD

**Issue by yekeqiang** [royrusso/elasticsearch-HQ#236]
i use elastic HQ as a plugin，when i open in web browser，the connect button always show diurnal circle，can't show cluster status, F12, show errors

my install command:

```
./plugin install royrusso/elasticsearch-HQ
```

my es version is 2.0.0

the error 
```
Uncaught SystaxError: missing ) after argument list

Uncaught TypeError: Cannot read Property 'addParser' of underfined

Uncaught TypeError: doFocus is not a function
```

**Comment by jieyongqing** [comment]
you should modify the file _site/index.html encoding to utf-8 , then it should work

**Comment by yekeqiang** [comment]
@jieyongqing  THS，use your method, have fix it
