### ISSUE TITLE
Feature request: 5.0.0 compatibility

### ISSUE THREAD

**Issue by bra-fsn** [royrusso/elasticsearch-HQ#267]
Hi,

As 5.0.0 GA is out, it would be very nice to have elasticsearch-HQ running on it.

**Comment by royrusso** [comment]
I'll look at it. My guess is that not much has changed in the plugin architecture, but I may be surprised here.

**Comment by royrusso** [comment]
"Site plugins removed
Site plugins have been removed. Site plugins should be reimplemented as Kibana plugins." 

My guess is that this breaks HQ.

**Comment by djzort** [comment]
:(

**Comment by djzort** [comment]
Quickest option for now would be to just distribute it as a zip file, and share the html and .js content via your web server software of choice?

**Comment by xbgmsharp** [comment]
- Deploy the archive into a documenr root of a web server.
- Allow CORS from the ES instance or on the proxy.
Done

A few feature need update, but over all it is working.
```
"reason":"request [/_cluster/state] contains unrecognized parameters: [filter_blocks] -> did you mean [filter_path]?, [filter_indices] -> did you mean [allow_no_indices]?, [filter_metadata] -> did you mean [filter_path]?, [filter_nodes] -> did you mean [filter_path]?, [filter_routing_table]"
```

**Comment by Tschebel** [comment]
/_nodes?all=true does not work too, seems to be /_nodes/_all now
```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_nodes] contains unrecognized parameter: [all]"}],"type":"illegal_argument_exception","reason":"request [/_nodes] contains unrecognized parameter: [all]"},"status":400}
```

**Comment by xbgmsharp** [comment]
Quick and dirty:
```
# sed s'/nodes?all=true/nodes\/_all/g' -i  js/all.min.js 
# sed 's/state?filter_nodes=false&filter_metadata=true&filter_routing_table=true&filter_blocks=true&filter_indices=true/state/g' -i  js/all.min.js 
# sed 's/?all=1/\/_all/g' -i  js/all.min.js
```

**Comment by boldandbusted** [comment]
https://github.com/royrusso/elasticsearch-HQ/pull/269 FYI.

**Comment by waqark3389** [comment]
@xbgmsharp @boldandbusted Will this be added to the next release?

**Comment by waqark3389** [comment]
@xbgmsharp Your fix does not replace "?all=true" - for example 

{return a?"/_nodes/"+a+"?all=true":"/_nodes/_all"}

I got "Unable to Read Node Information! " when clicking on a node. 

Very quick and dirty:

    # sed s'/?all=true//g' -i  js/all.min.js

**Comment by fbaligand** [comment]
@royrusso 
This would be great to just make a new github release named 5.0.0, with `"?all=true"` fix, and with a "binary attachment" containing only "_site" part.

In a longer term, a kibana plugin would be really great !
But I can imagine it's a *very* longer job :)

**Comment by xzer** [comment]
this may be an option to host old site plugins:

https://github.com/xzer/elasticsearch-plugin-hosting

**Comment by fbaligand** [comment]
I'm not sure to understand: it is standalone http server or a elasticsearch plugin which allow to host http content?

Fabien

**Comment by xzer** [comment]
It's a standalone server to help you hosting several site plugins at the same time.

**Comment by fbaligand** [comment]
OK. 
What does it bring compared to a classic http server like apache httpd or nginx?

**Comment by xzer** [comment]
1.  it ships an install script which makes download plugins a little bit simply, just like install plugins in the past 2.x ES.
2. without configuration, you can use it out of box.

**Comment by fbaligand** [comment]
Ok. Interesting 

Fabien

**Comment by fbaligand** [comment]
@mitchpenrod 
Could you create a 5.0.0 tag/release ?

**Comment by mitchpenrod** [comment]
@fbaligand I will be tagging a 5.0.0 in the next couple of days. However, as I have not yet fully tested every feature, I'm not comfortable saying it's release quality at the moment. Once I am, I will create a tag.

What's in `master` should be 95% of the way there so if you 5.x support, it should work. However, if you encounter bugs, feel free to open issues and I'll work to resolve them.

Thanks,
Mitch

**Comment by fbaligand** [comment]
Thanks for your work Mich!
I will test this version and give you feedback if I see bugs.

**Comment by fbaligand** [comment]
Hi @mitchpenrod ,

I just made some tests and here's the problems I met :
- blocker : When I click on a "node" to have node details, I see that HQ makes successful XHR requests... but it doesn't display node details page. The loading indicator stays indefinitely.
- in index "Administration" tab, the "Optimize Index" button fails. I think it should be rename to "Force merge Index" and call `_forcemerge` API.
