### ISSUE TITLE
ERROR: Unknown plugin royrusso/elasticsearch-HQ/v2.0.3

### ISSUE THREAD

**Issue by rogoit** [royrusso/elasticsearch-HQ#273]
Looks like the plugin is not found - is there a way to get only the code for the plugin folder

Elasticsearch 5.1.1

cmd
 sudo bin/elasticsearch-plugin install royrusso/elasticsearch-HQ/v2.0.3

**Comment by JoshuaAndrew** [comment]
(1) case 1
root@elastic:~# elasticsearch-plugin install  royrusso/elasticsearch-HQ
ERROR: Unknown plugin royrusso/elasticsearch-HQ

(2) case 2
root@elastic:~# elasticsearch-plugin install https://github.com/royrusso/elasticsearch-HQ
-> Downloading https://github.com/royrusso/elasticsearch-HQ
ERROR: `elasticsearch` directory is missing in the plugin zip

Anyone can help me?

**Comment by AndolsiZied** [comment]
you can download the plugin manually from this link : https://github.com/royrusso/elasticsearch-HQ/zipball/master and then run it in python as described ihere : https://www.elastic.co/fr/blog/running-site-plugins-with-elasticsearch-5-0

**Comment by avollmerhaus** [comment]
It's a bit unfortunate since the documented way of installing the plugin is broken, see http://www.elastichq.org/support_plugin.html

**Comment by hzruandd** [comment]
I tried above all, but it did not work. i think it not support the version of 5.0+

**Comment by mafarooq** [comment]
Getting  the same error for head, HQ and Kopf.
plugin install lmenezes/elasticsearch-kopf
I have ES version 5.2.2

**Comment by nmedelmehdi** [comment]
same error : 
elasticsearch-plugin install https://github.com/royrusso/elasticsearch-HQ/zipball/master ==> ERROR: `elasticsearch` directory is missing in the plugin zip

elasticsearch-plugin install royrusso/elasticsearch-HQ ==> ERROR: Unknown plugin royrusso/elasticsearch-HQ

**Comment by ruscon** [comment]
same error for 5.3.0:
```
bin/elasticsearch-plugin install https://github.com/royrusso/elasticsearch-HQ/zipball/master
-> Downloading https://github.com/royrusso/elasticsearch-HQ/zipball/master
[=================================================] 100%
ERROR: `elasticsearch` directory is missing in the plugin zip
```

**Comment by mitchpenrod** [comment]
Site plugins are not supported as of Elasticsearch 5.0 so ElasticHQ must be run as a standalone application. Since it's static HTML/CSS/JS you can run it from pretty much any web server. Setting up nginx or Apache is outside the scope of the documentation I can realistically provide.

Thanks,
Mitch
