### ISSUE TITLE
Add support for multiple ES clusters 

### ISSUE THREAD

**Issue by netanel246** [royrusso/elasticsearch-HQ#274]
We have a lot of elastic clusters and we want unified UI to monitor them all.
It will be great if HQ will support multiple ES clusters in one GUI.
The Marvel plugin (ElasticSearch monitoring) [support it](https://www.elastic.co/guide/en/x-pack/current/monitoring-cluster.html) and it works great.

**Comment by xzer** [comment]
The most simple way to achieve this is to allow specify target server address via path parameter, just like other plugins do.

head allow base_uri parameter and kopf allow location parameter. I also hope HQ could support this.

**Comment by mitchpenrod** [comment]
ElasticHQ supports a `url` GET parameter with the cluster URI, just like Head's `base_uri`. I use this to run multiple ElasticHQ instances from the same install.

This isn't a "unified UI", exactly, but it gives you quick access to all of them. Multi-cluster support in X-Pack is a pricey feature, so it's unlikely it will be something I can do in my spare time.

I do appreciate the suggestion but will be closing the ticket.

Thanks,
Mitch

**Comment by marcio-pessoa** [comment]
Is this project dead?

**Comment by royrusso** [comment]
For the most part, yes. I'll update the README
