### ISSUE TITLE
Elasticsearch 5.0 support release date?

### ISSUE THREAD

**Issue by rjurado01** [royrusso/elasticsearch-HQ#275]
There is a estimated Elasticsearch 5.0 supported version release date?

**Comment by DaRkRaGe** [comment]
Yeah I'm very interested too

**Comment by falkowich** [comment]
Looks like there is something going on there -> https://github.com/royrusso/elasticsearch-HQ/pull/269

**Comment by bluepuma77** [comment]
+1

**Comment by melkah** [comment]
+1

**Comment by raulk89** [comment]
+1

**Comment by cauepor** [comment]
@raulk89 plugins are not supported but u can remotely connect to it, u just need to allow CORS on your ES cluster. So, support for the metrics on 5.0 is still appreciatted. Would like to know when the resource will be available.

**Comment by joschi99** [comment]
+1

**Comment by saurfangg** [comment]
+1

**Comment by jonesn** [comment]
+1

**Comment by jeffhuys** [comment]
This repository seems.. dead.. 😢

**Comment by mitchpenrod** [comment]
This is currently being worked on. I apologize for the delay, but I have not had much spare time lately to devote to any outside projects.

So far things are looking good. I'll probably cut a release this weekend.

**Comment by mitchpenrod** [comment]
I've merged 5.x support to master. I know there are probably still a few bugs as I haven't had a chance to test out everything, so I won't cut a 5.0.0 tag just yet, but the basic functionality is there.

I'm closing this issue. If you find a bug in the master branch, then please open a new issue.
